---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kafka-lab
spec:
  replicas: 1
  selector:
    matchLabels:
      app: KAFKA
  template:
    metadata:
      name: kafka-lab
      labels:
        app: KAFKA
    spec:
      hostname: kafka
      containers:
        - name: kafka
          image: confluentinc/cp-kafka:7.3.0
          ports:
            - containerPort: 29092
          volumeMounts:
            - mountPath: /etc/kafka/secrets
              name: kafka-secrets-vol
            - mountPath: /var/lib/kafka/data
              name: kafka-data-vol
          env:
            - name: KAFKA_BROKER_ID
              value: "1"
            - name: KAFKA_ZOOKEEPER_CONNECT
              value: "zookeeper-service:32181"
            - name: KAFKA_ADVERTISED_LISTENERS
              value: "PLAINTEXT://kafka:9092,PLAINTEXT_HOST://localhost:29092"
            - name: KAFKA_LISTENER_SECURITY_PROTOCOL_MAP
              value: "PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT"
            - name: KAFKA_INTER_BROKER_LISTENER_NAME
              value: "PLAINTEXT"
            - name: KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR
              value: "1"
      volumes:
        - name: kafka-secrets-vol
          persistentVolumeClaim:
            claimName: kafka-secrets-pvc
        - name: kafka-data-vol
          persistentVolumeClaim:
            claimName: kafka-data-pvc
      restartPolicy: Always
