apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: kafka-secrets-pvc
spec:
  storageClassName: ""
  accessModes:
    - ReadWriteOnce
  volumeName: kafka-secrets-pv
  resources:
    requests:
      storage: 16Mi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: kafka-data-pvc
spec:
  storageClassName: ""
  accessModes:
    - ReadWriteOnce
  volumeName: kafka-data-pv
  resources:
    requests:
      storage: 16Gi
