apiVersion: v1
kind: Service
metadata:
  name: kafka-service
spec:
  selector:
    app: KAFKA
  type: NodePort
  ports:
    - name: kafka-listener-port
      protocol: TCP
      port: 30092
      targetPort: 30092
      nodePort: 30092
    - name: kafka-interbroker-port
      protocol: TCP
      port: 9092
      targetPort: 9092
      nodePort: 30093
