apiVersion: v1
kind: Service
metadata:
  name: kafka1-service
spec:
  selector:
    app: KAFKA1
  type: NodePort
  ports:
    - name: kafka-listener-port
      protocol: TCP
      port: 29092
      targetPort: 29092
      nodePort: 30092
    - name: kafka-interbroker-port
      protocol: TCP
      port: 9092
      targetPort: 9092
---
apiVersion: v1
kind: Service
metadata:
  name: kafka2-service
spec:
  selector:
    app: KAFKA2
  type: NodePort
  ports:
    - name: kafka-listener-port
      protocol: TCP
      port: 29092
      targetPort: 29092
      nodePort: 30093
    - name: kafka-interbroker-port
      protocol: TCP
      port: 9092
      targetPort: 9092
---
apiVersion: v1
kind: Service
metadata:
  name: kafka3-service
spec:
  selector:
    app: KAFKA3
  type: NodePort
  ports:
    - name: kafka-listener-port
      protocol: TCP
      port: 29092
      targetPort: 29092
      nodePort: 30094
    - name: kafka-interbroker-port
      protocol: TCP
      port: 9092
      targetPort: 9092
