apiVersion: v1
kind: PersistentVolume
metadata:
  name: zookeeper-secrets-pv
spec:
  storageClassName: ""
  volumeMode: Filesystem
  capacity:
    storage: 16Mi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: {{ .Values.local.volumes.path }}/zookeeper/secrets
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: zookeeper-data-pv
spec:
  storageClassName: ""
  volumeMode: Filesystem
  capacity:
    storage: 16Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: {{ .Values.local.volumes.path }}/zookeeper/data
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: zookeeper-log-pv
spec:
  storageClassName: ""
  volumeMode: Filesystem
  capacity:
    storage: 2Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: {{ .Values.local.volumes.path }}/zookeeper/log
