apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: zookeeper-secrets-pvc
spec:
  storageClassName: ""
  accessModes:
    - ReadWriteOnce
  volumeName: zookeeper-secrets-pv
  resources:
    requests:
      storage: 16Mi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: zookeeper-data-pvc
spec:
  storageClassName: ""
  accessModes:
    - ReadWriteOnce
  volumeName: zookeeper-data-pv
  resources:
    requests:
      storage: 16Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: zookeeper-log-pvc
spec:
  storageClassName: ""
  accessModes:
    - ReadWriteOnce
  volumeName: zookeeper-log-pv
  resources:
    requests:
      storage: 2Gi
