apiVersion: v1
kind: Service
metadata:
  name: zookeeper-service
spec:
  selector:
    app: ZOOKEEPER
  type: NodePort
  ports:
    - name: zookeeper-client-port
      protocol: TCP
      port: 2181
      targetPort: 2181
      nodePort: 32181
