apiVersion: v1
kind: Service
metadata:
  name: zookeeper1-service
spec:
  selector:
    app: ZOOKEEPER1
  type: NodePort
  ports:
    - name: zookeeper-client-port
      protocol: TCP
      port: 2181
      targetPort: 2181
    - name: zookeeper-leader-followers-port
      protocol: TCP
      port: 2888
      targetPort: 2888
    - name: zookeeper-leader-election-port
      protocol: TCP
      port: 3888
      targetPort: 3888
---
apiVersion: v1
kind: Service
metadata:
  name: zookeeper2-service
spec:
  selector:
    app: ZOOKEEPER2
  type: NodePort
  ports:
    - name: zookeeper-client-port
      protocol: TCP
      port: 2181
      targetPort: 2181
    - name: zookeeper-leader-followers-port
      protocol: TCP
      port: 2888
      targetPort: 2888
    - name: zookeeper-leader-election-port
      protocol: TCP
      port: 3888
      targetPort: 3888
---
apiVersion: v1
kind: Service
metadata:
  name: zookeeper3-service
spec:
  selector:
    app: ZOOKEEPER3
  type: NodePort
  ports:
    - name: zookeeper-client-port
      protocol: TCP
      port: 2181
      targetPort: 2181
    - name: zookeeper-leader-followers-port
      protocol: TCP
      port: 2888
      targetPort: 2888
    - name: zookeeper-leader-election-port
      protocol: TCP
      port: 3888
      targetPort: 3888
