net.pryszawa.kafkalab:
  kafka:
    bootstrap-servers-config: localhost:30093
    truststore.location: ${net.pryszawa.kafkalab.dir}/certificates/kafka1.truststore.jks
    truststore.password: "kafka1"
